# Localization Language Selection
# Default language is english if empty or "en".
# To switch language put in the name of the language-file (e.g. "de" for de.yml)
language: "en"

# Use MySQL instead of SQLite?
use-mysql: false

# Login details if backend is mysql
dbUsername: "root"
dbPassword: ""
dbHostname: "127.0.0.1"
dbName: "ip-check"
dbPort: 3306

# Set this to false if you want the tables to be regenerated
dbGenerated: false

# Should use Login Checking?
notify-on-login: true

# Should warn when a banned player attempts to join
warn-on-rejoin-attempt: false

# Should show descriptive notifications?
descriptive-notice: false

# Should use Secure Mode?
# Secure Mode is a feature of IP-Check that actively monitors and blocks
# players from making too many accounts on your server (limit controlled by
# secure-kick-threshold).
secure-mode: true

# Should this plugin be your default ban/kick manager?
should-manage-bans: true

# Should use Active Mode?
# Active Mode is a feature of IP-Check that actively bans new accounts that
# join your server if they connect from a banned IP-Address. This helps keep
# IP-Check's database and your server's ban list up to date.
# NOTE: This function will not work if should-mange-bans is false.
active-mode: true

# Should Ban Account when kicked by Secure Mode?
# NOTE: This function will not work if should-manage-bans is false.
should-ban-on-secure-kick: false

# Set a minimum number of accounts to have before being notified
min-account-notify-threshold: 1

# Set a minimum number of accounts to have before being kicked
secure-kick-threshold: 1

# Set Secure Kick Message
secure-kick-message: "Múltiplas contas não são permitidas."

# Set Ban Message
ban-message: "Banido por Multi-Conta."

# Set Kick Message
kick-message: "Expulso do server."

# Disable Update Detection
disable-update-detection: false

# Disable Metrics Monitoring
disable-metrics-monitoring: false

# GeoIP Services Main Control
use-geoip-services: true

# Allow IP-Check to automatically download the GeoIP Database
allow-geoip-download: true

# Allow the use of the Country Blacklist
use-country-blacklist: true

# Make Country Blacklist act as Whitelist
use-blacklist-as-whitelist: false

# Which countries do you want to block from joining your server?
country-blacklist: []

# What message do you want to display to people who's country is blocked?
blocked-message: "Seu país foi bloqueado de acessar o servidor"

# MC Hammer!
config-version: 5
